accounts:
  - name: root
    coins: ["1100000000stake"]
    mnemonic: retreat uphold table initial liquid glow debris carbon salon expire mystery entry blue skirt differ wing general only human scout fish pipe asthma base
validator:
  name: root
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
init:
  client:
    keyring-backend: "test"