accounts:
  - name: root
    coins: ["1000000000000token", "100000000000stake"]
  - name: alice
    coins: ["10000token", "100000000stake"]
validator:
  name: root
  staked: "100000000000stake"
  name: alice
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
init:
  client:
    keyring-backend: "test"