// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: blockchain/stock_transaction.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type BoughtStock struct {
	Amount int32  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Count  int32  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Date   string `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
}

func (m *BoughtStock) Reset()         { *m = BoughtStock{} }
func (m *BoughtStock) String() string { return proto.CompactTextString(m) }
func (*BoughtStock) ProtoMessage()    {}
func (*BoughtStock) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c7f749cf77905bb, []int{0}
}
func (m *BoughtStock) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BoughtStock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BoughtStock.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BoughtStock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoughtStock.Merge(m, src)
}
func (m *BoughtStock) XXX_Size() int {
	return m.Size()
}
func (m *BoughtStock) XXX_DiscardUnknown() {
	xxx_messageInfo_BoughtStock.DiscardUnknown(m)
}

var xxx_messageInfo_BoughtStock proto.InternalMessageInfo

func (m *BoughtStock) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *BoughtStock) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *BoughtStock) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

type HoldingStock struct {
	Code          string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Count         int32  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	PurchasAmount int32  `protobuf:"varint,3,opt,name=purchas_amount,json=purchasAmount,proto3" json:"purchas_amount,omitempty"`
}

func (m *HoldingStock) Reset()         { *m = HoldingStock{} }
func (m *HoldingStock) String() string { return proto.CompactTextString(m) }
func (*HoldingStock) ProtoMessage()    {}
func (*HoldingStock) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c7f749cf77905bb, []int{1}
}
func (m *HoldingStock) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HoldingStock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HoldingStock.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HoldingStock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HoldingStock.Merge(m, src)
}
func (m *HoldingStock) XXX_Size() int {
	return m.Size()
}
func (m *HoldingStock) XXX_DiscardUnknown() {
	xxx_messageInfo_HoldingStock.DiscardUnknown(m)
}

var xxx_messageInfo_HoldingStock proto.InternalMessageInfo

func (m *HoldingStock) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *HoldingStock) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *HoldingStock) GetPurchasAmount() int32 {
	if m != nil {
		return m.PurchasAmount
	}
	return 0
}

type StockTransaction struct {
	Creator       string          `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	HoldingStocks []*HoldingStock `protobuf:"bytes,2,rep,name=holding_stocks,json=holdingStocks,proto3" json:"holding_stocks,omitempty"`
}

func (m *StockTransaction) Reset()         { *m = StockTransaction{} }
func (m *StockTransaction) String() string { return proto.CompactTextString(m) }
func (*StockTransaction) ProtoMessage()    {}
func (*StockTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c7f749cf77905bb, []int{2}
}
func (m *StockTransaction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StockTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StockTransaction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StockTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StockTransaction.Merge(m, src)
}
func (m *StockTransaction) XXX_Size() int {
	return m.Size()
}
func (m *StockTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_StockTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_StockTransaction proto.InternalMessageInfo

func (m *StockTransaction) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *StockTransaction) GetHoldingStocks() []*HoldingStock {
	if m != nil {
		return m.HoldingStocks
	}
	return nil
}

func init() {
	proto.RegisterType((*BoughtStock)(nil), "chainstockproject.blockchain.blockchain.BoughtStock")
	proto.RegisterType((*HoldingStock)(nil), "chainstockproject.blockchain.blockchain.HoldingStock")
	proto.RegisterType((*StockTransaction)(nil), "chainstockproject.blockchain.blockchain.StockTransaction")
}

func init() {
	proto.RegisterFile("blockchain/stock_transaction.proto", fileDescriptor_5c7f749cf77905bb)
}

var fileDescriptor_5c7f749cf77905bb = []byte{
	// 306 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0xed, 0xf4, 0xef, 0xa3, 0xd3, 0xaf, 0x45, 0x06, 0x91, 0xac, 0x86, 0x12, 0x10, 0xbb, 0x31,
	0x05, 0xc5, 0x95, 0x2b, 0xbb, 0x72, 0x27, 0x44, 0xdd, 0x88, 0x10, 0x26, 0x93, 0x90, 0x89, 0x6d,
	0x73, 0xc3, 0xcc, 0x04, 0xf4, 0x15, 0x5c, 0xf9, 0x58, 0x2e, 0xbb, 0x74, 0x29, 0xc9, 0x8b, 0x88,
	0x37, 0x91, 0x64, 0x23, 0xb8, 0xbb, 0xe7, 0x9c, 0x99, 0x73, 0xee, 0x0f, 0x75, 0xc3, 0x2d, 0xc8,
	0x8d, 0x54, 0x22, 0xcd, 0x56, 0xc6, 0x82, 0xdc, 0x04, 0x56, 0x8b, 0xcc, 0x08, 0x69, 0x53, 0xc8,
	0xbc, 0x5c, 0x83, 0x05, 0x76, 0x82, 0x32, 0xaa, 0xb9, 0x86, 0xa7, 0x58, 0x5a, 0xaf, 0xfd, 0xd5,
	0x29, 0xdd, 0x1b, 0x3a, 0x5d, 0x43, 0x91, 0x28, 0x7b, 0xfb, 0xfd, 0x96, 0x1d, 0xd1, 0xb1, 0xd8,
	0x41, 0x91, 0x59, 0x87, 0x2c, 0xc8, 0x72, 0xe4, 0x37, 0x88, 0x1d, 0xd2, 0x91, 0x44, 0xba, 0x8f,
	0x74, 0x0d, 0x18, 0xa3, 0xc3, 0x48, 0xd8, 0xd8, 0x19, 0x2c, 0xc8, 0x72, 0xe2, 0x63, 0xed, 0x06,
	0xf4, 0xff, 0x35, 0x6c, 0xa3, 0x34, 0x4b, 0x6a, 0x47, 0x46, 0x87, 0x12, 0xa2, 0x18, 0xfd, 0x26,
	0x3e, 0xd6, 0xbf, 0xb8, 0x1d, 0xd3, 0x79, 0x5e, 0x68, 0xa9, 0x84, 0x09, 0x9a, 0x1e, 0x06, 0x28,
	0xcf, 0x1a, 0xf6, 0x0a, 0x49, 0xf7, 0x95, 0xd0, 0x03, 0xb4, 0xbe, 0x6b, 0xa7, 0x66, 0x0e, 0xfd,
	0x27, 0x75, 0x2c, 0x2c, 0xe8, 0x26, 0xe8, 0x07, 0xb2, 0x47, 0x3a, 0x57, 0x75, 0x3f, 0x01, 0xae,
	0xc3, 0x38, 0xfd, 0xc5, 0x60, 0x39, 0x3d, 0xbb, 0xf0, 0xfe, 0xb8, 0x22, 0xaf, 0x3b, 0x8e, 0x3f,
	0x53, 0x1d, 0x64, 0xd6, 0xf7, 0xef, 0x25, 0x27, 0xfb, 0x92, 0x93, 0xcf, 0x92, 0x93, 0xb7, 0x8a,
	0xf7, 0xf6, 0x15, 0xef, 0x7d, 0x54, 0xbc, 0xf7, 0x70, 0x99, 0xa4, 0x56, 0x15, 0xa1, 0x27, 0x61,
	0xb7, 0x6a, 0x93, 0x4e, 0x9b, 0xa8, 0x55, 0xe7, 0x86, 0xcf, 0x5d, 0x60, 0x5f, 0xf2, 0xd8, 0x84,
	0x63, 0xbc, 0xe2, 0xf9, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe6, 0x74, 0x9f, 0x28, 0xeb, 0x01,
	0x00, 0x00,
}

func (m *BoughtStock) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BoughtStock) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BoughtStock) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Date) > 0 {
		i -= len(m.Date)
		copy(dAtA[i:], m.Date)
		i = encodeVarintStockTransaction(dAtA, i, uint64(len(m.Date)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Count != 0 {
		i = encodeVarintStockTransaction(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x10
	}
	if m.Amount != 0 {
		i = encodeVarintStockTransaction(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *HoldingStock) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HoldingStock) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HoldingStock) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PurchasAmount != 0 {
		i = encodeVarintStockTransaction(dAtA, i, uint64(m.PurchasAmount))
		i--
		dAtA[i] = 0x18
	}
	if m.Count != 0 {
		i = encodeVarintStockTransaction(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Code) > 0 {
		i -= len(m.Code)
		copy(dAtA[i:], m.Code)
		i = encodeVarintStockTransaction(dAtA, i, uint64(len(m.Code)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *StockTransaction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StockTransaction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StockTransaction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.HoldingStocks) > 0 {
		for iNdEx := len(m.HoldingStocks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.HoldingStocks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintStockTransaction(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintStockTransaction(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintStockTransaction(dAtA []byte, offset int, v uint64) int {
	offset -= sovStockTransaction(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BoughtStock) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Amount != 0 {
		n += 1 + sovStockTransaction(uint64(m.Amount))
	}
	if m.Count != 0 {
		n += 1 + sovStockTransaction(uint64(m.Count))
	}
	l = len(m.Date)
	if l > 0 {
		n += 1 + l + sovStockTransaction(uint64(l))
	}
	return n
}

func (m *HoldingStock) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Code)
	if l > 0 {
		n += 1 + l + sovStockTransaction(uint64(l))
	}
	if m.Count != 0 {
		n += 1 + sovStockTransaction(uint64(m.Count))
	}
	if m.PurchasAmount != 0 {
		n += 1 + sovStockTransaction(uint64(m.PurchasAmount))
	}
	return n
}

func (m *StockTransaction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovStockTransaction(uint64(l))
	}
	if len(m.HoldingStocks) > 0 {
		for _, e := range m.HoldingStocks {
			l = e.Size()
			n += 1 + l + sovStockTransaction(uint64(l))
		}
	}
	return n
}

func sovStockTransaction(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozStockTransaction(x uint64) (n int) {
	return sovStockTransaction(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BoughtStock) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStockTransaction
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BoughtStock: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BoughtStock: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStockTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStockTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Date", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStockTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStockTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStockTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Date = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStockTransaction(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStockTransaction
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HoldingStock) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStockTransaction
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HoldingStock: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HoldingStock: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStockTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStockTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStockTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Code = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStockTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PurchasAmount", wireType)
			}
			m.PurchasAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStockTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PurchasAmount |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipStockTransaction(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStockTransaction
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StockTransaction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowStockTransaction
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StockTransaction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StockTransaction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStockTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthStockTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthStockTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HoldingStocks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowStockTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthStockTransaction
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthStockTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HoldingStocks = append(m.HoldingStocks, &HoldingStock{})
			if err := m.HoldingStocks[len(m.HoldingStocks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipStockTransaction(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthStockTransaction
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipStockTransaction(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowStockTransaction
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStockTransaction
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowStockTransaction
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthStockTransaction
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupStockTransaction
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthStockTransaction
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthStockTransaction        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowStockTransaction          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupStockTransaction = fmt.Errorf("proto: unexpected end of group")
)
